id: PFB08D0D3
initial_creation_type: ocr
source_metadata:
  volumes:
    7543a4e16cef465a86ff987f1e075444:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: འཕགས་པ་ལག་ན་རྡོ་རྗེ་གོས་སྔོན་པོ་ཅན་གྱི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག་ཐམས་ཅད་རྫོགས་པ།
      total_pages: 1853
      volume_number: 25
